name: Bug Report
description: Report a bug or unexpected behavior with reproduction steps.
title: "BUG: [Short Description of Bug]"
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible to help us reproduce and fix it.
  - type: input
    id: summary
    attributes:
      label: Brief Description
      description: A one-line description of the issue.
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to replicate the issue.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, model versions, browser, etc.
  - type: textarea
    id: logs
    attributes:
      label: Logs / Traceback
      description: Paste relevant logs or error traces (omit secrets).
      render: shell
  - type: input
    id: workaround
    attributes:
      label: Workaround (if any)
      description: Have you found a temporary workaround? Describe it.
